import type { ReactNode } from 'react';

import { Noto_Sans, Noto_Sans_JP } from 'next/font/google';
import './globals.css';

const noto = Noto_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-noto-sans',
});

const notojp = Noto_Sans_JP({
  weight: ['400', '700'],
  preload: false,
  display: 'swap',
  variable: '--font-noto-sans-jp',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }): ReactNode => (
  <html lang="ja">
    <body
      className={`${noto.variable} ${notojp.variable} font-NotoSansJP font-NotoSans`}
    >
      {children}
    </body>
  </html>
);

export default RootLayout;
